liveness:
  kafka:
    #Flag to enable/disable the scheduled periodic offset movement check
    #Optional: default is true
    scheduled: true
    #The period in seconds between checks
    #Optional: default is 600
    check-period-sec: 600
    #The initial delay in seconds before the first check
    #Optional: default is 600
    check-initial-delay-sec: 600
